<a href="https://colab.research.google.com/github/SIDDH4RTH245/sales-forecasting-ml-project/blob/main/notebooks/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sales Forecasting Project
# Step 1: Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/jbrownlee/Datasets/master/monthly-car-sales.csv")

df.head()

     Month  Sales
0  1960-01   6550
1  1960-02   8728
2  1960-03  12026
3  1960-04  14395
4  1960-05  14587

In [3]:
df.columns = ["Month", "Sales"]

In [4]:
df["Month"] = pd.to_datetime(df["Month"])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Month   108 non-null    datetime64[ns]
 1   Sales   108 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.8 KB

In [6]:
df.isnull().sum()

Month    0
Sales    0
dtype: int64

In [7]:
df.head()

       Month  Sales
0 1960-01-01   6550
1 1960-02-01   8728
2 1960-03-01  12026
3 1960-04-01  14395
4 1960-05-01  14587

In [9]:
df.to_csv("sales_cleaned.csv")